/* Reads the real engine out of source.html and writes data.js, so every number,
   name, colour, glyph and sentence in these mockups is the engine's own on the
   day it was run. Nothing here reads a profile except through loadP.

     NODE_PATH=/opt/node22/lib/node_modules node mockups/release-redesign/extract.js

   The one thing the engine does not carry yet is a subject for an imprint. The
   sniffer is said to record one; at the commit these were cut from it did not,
   so the subjects below are marked illustrative and the connector word is the
   proposal in data.js PREP. */
const {chromium}=require('playwright');
const path=require('path'), fs=require('fs');
const FILE='file://'+path.resolve(__dirname,'../../source.html')+'?dev=1';
const OUT=path.resolve(__dirname,'data.js');

/* who, which three addresses, and the subject each would carry. null is an
   imprint with no subject, which reads 'myself'. */
const CAST=[
 {nm:'Gordon',key:'gordon',pick:[53,9,1],subj:{53:'my boss',9:'my firm',1:null}},
 {nm:'Derek',key:'derek',pick:[31,33,1],subj:{31:'my father',33:'my coach',1:null}},
 {nm:'Angela',key:'angela',pick:[1,107,5],subj:{1:'my mother',107:'my friends',5:null}},
 {nm:'Sofia',key:'sofia',pick:[31,65,66],subj:{31:'my clients',65:'my teacher',66:'my sister'}}];

(async()=>{
 const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
 const p=await b.newPage({viewport:{width:1600,height:1000}});
 const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.goto(FILE); await p.waitForTimeout(6500);
 const D=await p.evaluate(cast=>{
  var out={people:[],stem:C3_STEM,truth:C3_TRUTH,verbs:C3_VERB,cooling:COOLING,welcome:REL_WELCOME,
   opening:OPENING,settle:REL_SETTLE_S,side:REL_SIDE,entry:REL_ENTRY,
   pole:C3_POLE.map(function(x){return {k:x.k,nm:x.nm,ch:x.ch,ans:x.ans,of:x.of,en:x.en};}),
   chan:CHAN,pal:PAL,glyph:SEATGLYPH,
   child:CHILD.map(function(c){return {nm:c.nm,opp:c.opp,ic:c.ic};}),
   hz:{}};
  ['Root','Sacral','Solar','Heart','Throat','3rd Eye','Crown'].forEach(function(s){out.hz[s]=seatHz(s);});
  PAL_LIGHT&&(out.palLight=PAL_LIGHT);
  cast.forEach(function(c){
   var i=PEOPLE.findIndex(function(x){return x.nm===c.nm;}); loadP(i); compute();
   var P=PEOPLE[i];
   RUN.dose=100; relPick(c.pick); RUN.pace=1;
   var addrs=c.pick.map(function(id){
    var n=BY[id], opp=relOpp(n), blocks={};
    CHAN.forEach(function(ch){
     var at={n:n,ch:ch,line:0}, key=ch[0]+ch[2];
     blocks[key]={head:relStepAt(at,0).text,
      passes:[1,2,3,4].map(function(k){return relStepAt(at,k).text;})};});
    return {i:n.i,k:n.k,b:n.b,n:n.n,cf:n.cf,sq:n.sq,pct:Math.round(n.sq*10),
     col:seatCol(n.b),glyph:SEATGLYPH[n.b],opp:opp,subject:c.subj[id]||null,blocks:blocks};});
   var cnt=relCounts();
   out.people.push({key:c.key,nm:c.nm,age:P.age,role:P.role,says:P.says,addrs:addrs,
    plan:RUN.plan.slice(),dose:RUN.dose,total:cnt.of,totalTruth:cnt.putOf,
    runSeconds:Math.round(relSecFrom(null))});
   relClose();});
  return out;},CAST);
 if(errs.length)console.log('page errors',errs);
 fs.writeFileSync(OUT,'/* generated by extract.js from source.html, do not edit */\nwindow.D='+JSON.stringify(D)+';\n');
 console.log('wrote',OUT,fs.statSync(OUT).size,'bytes;',D.people.map(x=>x.nm+' '+x.plan.length+' blocks, '+x.runSeconds+' s').join(', '));
 await b.close();
})();
