/* THE FUZZY CORPUS, round QZ follow on. Written to measure the owner's own bug
   report before anything was changed: "I'm able to talk about painful
   situations and the sniffer's not picking up because the sniffer is too
   specific... it needs to be fuzzier. The rules need to be looser."

   WRITTEN BEFORE THE SYNONYM TABLE, and the order matters. The previous
   recall measurement this repository holds (TASKS.md 0j, SN3) recorded that
   its frames were written after reading the voices they were measured on, so
   its number was in sample and an upper bound. This corpus was written first
   and frozen; the table was then built against the DEV half only, and the
   HELD half was read once, at the end. It is still written by the same seat
   that wrote the table, so even the held half is author correlated, and that
   is said here rather than discovered.

   Each painful line carries the seats a reasonable reader would accept, by
   the lexicon's own conventions (lexicon.js and the seat comments in it):
     root    fear, safety, panic, the body bracing
     solar   anger, overwhelm, exhaustion, and self worth (the round GR family)
     sacral  being judged, disgust, nausea, compulsion
     heart   grief, loss, loneliness, rejection, sadness
     throat  unheard, silenced, lied to, betrayed, dismissed
     eye     rumination, distrust
     crown   meaninglessness, numbness, disconnection
   More than one seat is often right, so the label is a set and a line is
   counted right when the heaviest seat it lights is in that set.

   The quiet lines are what must NOT light. Three kinds, reported apart:
     plain    ordinary days with nothing in them
     warm     good days, including words whose negation is a pain word
     trap     words that mean a feeling in one sense and nothing in another,
              which is exactly where a looser rule goes wrong
   No line in the quiet set uses a pain word in its pain sense. */
var PAIN=[
 /* dev and held alternate, so each half has every family in it */
 ['My dad passed when I was twelve and nobody ever talked about it again.', ['heart','throat']],
 ['I sat in the car outside the hospital for an hour because I could not make myself go in.', ['root','heart']],
 ['Since the divorce the house is so quiet I leave the TV on just to hear a voice.', ['heart']],
 ['I keep waiting for the phone to ring and it never does.', ['heart']],
 ['I don’t feel safe in my own home anymore.', ['root']],
 ['Every time I hear his car in the driveway my whole body goes stiff.', ['root','throat']],
 ['I can’t sleep, I lie there with my heart racing until 4am.', ['root','eye']],
 ['I’m so worried about money that I feel sick most mornings.', ['root','sacral']],
 ['He screamed at me in front of the kids and I just stood there.', ['solar','root','throat']],
 ['I was so mad I wanted to put my fist through the wall.', ['solar']],
 ['My boss takes credit for everything I do and I’m sick of it.', ['solar','throat']],
 ['I get irritated by the smallest things lately and I snap at everyone.', ['solar']],
 ['I feel like such a failure compared to my brother.', ['solar','sacral']],
 ['I’m useless, I can’t do anything right.', ['solar','sacral']],
 ['I was bullied all through school and I still flinch when people laugh near me.', ['sacral','root','solar']],
 ['My mother made fun of my weight in front of everyone at Christmas.', ['sacral','solar']],
 ['Nobody at work listens to a word I say.', ['throat']],
 ['I tried to explain and he just talked right over me again.', ['throat']],
 ['She lied to my face for two years and I believed her.', ['throat']],
 ['I found the messages on his phone and my stomach dropped.', ['throat','sacral','heart']],
 ['I keep going over the conversation in my head all night.', ['eye']],
 ['I can’t switch my brain off, the thoughts just keep spinning.', ['eye']],
 ['Nothing feels real anymore, I’m just going through the days.', ['crown']],
 ['I don’t see the point in getting up some mornings.', ['crown','heart','solar']],
 ['I’m exhausted all the time and even sleep doesn’t help.', ['solar']],
 ['I’m completely worn out from looking after Mum.', ['solar']],
 ['Work is piling up and I feel like I’m going under.', ['solar']],
 ['I had a full meltdown in the supermarket car park.', ['solar','root']],
 ['I miss her every single day.', ['heart']],
 ['We lost the baby at twenty weeks.', ['heart']],
 ['My best friend stopped speaking to me and I don’t even know why.', ['heart']],
 ['I was left out of the wedding party and it really stung.', ['heart']],
 ['I feel invisible in my own family.', ['throat','heart']],
 ['I never felt loved by my father.', ['heart']],
 ['I don’t feel good enough for him.', ['sacral','solar']],
 ['I’m terrified something will happen to the kids.', ['root']],
 ['I’ve been having panic attacks on the train to work.', ['root']],
 ['I flinch whenever someone raises their voice.', ['root','solar']],
 ['He hit me and then cried and said sorry.', ['root','solar','heart']],
 ['I was abused as a kid and I’ve never told anyone.', ['root','throat']],
 ['I hate myself for letting it happen.', ['throat','solar','sacral']],
 ['I feel disgusting after I binge.', ['sacral']],
 ['I can’t stop eating when I’m stressed.', ['sacral','root']],
 ['I drink every night to take the edge off.', ['sacral']],
 ['I keep checking my phone to see if she’s read my message.', ['sacral','eye']],
 ['I’m dreading the meeting on Monday.', ['root']],
 ['I get this tight knot in my stomach before every shift.', ['sacral','root']],
 ['There is a lump in my throat every time I try to talk about it.', ['throat']],
 ['My shoulders have been up around my ears for weeks.', ['throat','root']],
 ['I can’t breathe properly when I think about the court date.', ['root']],
 ['I cried in the shower so nobody would hear me.', ['heart']],
 ['I’ve been crying on and off all week.', ['heart']],
 ['I feel so down and I can’t shake it.', ['heart']],
 ['I’ve been really depressed since the move.', ['heart','crown']],
 ['Honestly I’m not okay.', ['heart']],
 ['I feel stuck and trapped and I can’t see a way out.', ['heart','root','solar']],
 ['I feel so helpless watching him get worse.', ['heart']],
 ['I’m furious that they let him get away with it.', ['solar']],
 ['I resent having to carry everyone.', ['solar']],
 ['I’m so frustrated with myself.', ['solar']],
 ['He cheated on me with my best friend.', ['throat','heart']],
 ['They went behind my back and gave the job to someone else.', ['throat']],
 ['I was humiliated in front of the whole team.', ['solar','sacral']],
 ['I felt so stupid for trusting him.', ['solar']],
 ['I feel guilty for being relieved she’s gone.', ['solar','heart']],
 ['I regret every word I said to her that night.', ['heart','solar']],
 ['I’m ashamed of where I come from.', ['solar','sacral']],
 ['I feel judged every time I walk into that office.', ['sacral']],
 ['They treat me like I’m nothing.', ['solar','throat','sacral']],
 ['I feel completely alone even when I’m with people.', ['heart']],
 ['I have nobody to talk to about this.', ['heart','throat']],
 ['My kids don’t call anymore.', ['heart']],
 ['I feel like a burden to everyone around me.', ['solar','sacral']],
 ['I’m scared I’ll end up like my mother.', ['root']],
 ['I’m always on edge, waiting for the next thing to go wrong.', ['root']],
 ['I get anxious just opening my emails.', ['root']],
 ['The diagnosis came back and I just went numb.', ['sacral','crown']],
 ['I feel nothing anymore, not even at my son’s birthday.', ['crown','sacral']],
 ['I feel disconnected from everyone, like I’m behind glass.', ['crown']],
 ['I don’t know who I am anymore.', ['crown','heart']],
 ['My life feels pointless.', ['crown']],
 ['I have no motivation to do anything.', ['solar','crown']],
 ['I can’t get out of bed most days.', ['solar','heart','crown']],
 ['I’m running on fumes.', ['solar']],
 ['I’m overwhelmed and I can’t keep up with any of it.', ['solar']],
 ['I can’t cope with all of this on my own.', ['solar','heart']],
 ['My partner never lets me finish a sentence.', ['throat']],
 ['I swallowed it again rather than start another fight.', ['throat']],
 ['I didn’t say anything, I never do.', ['throat']],
 ['I can’t trust anyone after what happened.', ['eye']],
 ['I keep second guessing every decision I make.', ['eye']],
 ['I replay the accident over and over.', ['eye','root']],
 ['I lost my job and I haven’t told my wife.', ['heart','throat','root']],
 ['The landlord gave us two weeks to get out.', ['root']],
 ['My sister won’t speak to me since the funeral.', ['heart']],
 ['I feel rejected every time she pulls away.', ['heart']],
 ['He walked out on us when I was six.', ['heart']],
 ['I was so embarrassed I wanted the floor to swallow me.', ['solar','heart']],
 ['I feel so insecure next to the other mums.', ['solar']],
 ['I’m frightened of being on my own at night.', ['root']],
 ['I had a breakdown last spring and I’m scared it’s coming back.', ['root','solar']],
 ['I’m heartbroken that it’s over.', ['heart']],
 ['I’m grieving the life I thought I’d have.', ['heart']],
 ['Everyone else seems to be moving on and I’m stuck in the same place.', ['heart','crown','solar']],
 ['Nobody came to my birthday.', ['heart']],
 ['I feel unwanted.', ['heart']],
 ['I was told I was too much my whole life.', ['sacral','throat','solar']],
 ['I’m disgusted with how I spoke to her.', ['sacral','throat']],
 ['I can’t relax, even on holiday.', ['root','throat']],
 ['I’m stressed out of my mind about the exams.', ['root','solar']],
 ['I feel like I’m drowning in debt.', ['solar','root']],
 ['I’m bitter about how it all ended.', ['solar']],
 ['My chest goes tight when I see her name come up.', ['heart']],
 ['I shake before every presentation.', ['root']],
 ['I just feel empty inside.', ['sacral','crown']],
 ['I was let down again by the one person I counted on.', ['heart','throat']],
 ['I feel worthless when he ignores me.', ['solar','throat']],
 ['I’m afraid to tell anyone how bad it is.', ['root','throat']],
 ['I’ve been on my own since he died.', ['heart']]];

var QUIET={
 plain:[
  'I made a cup of tea and read the paper.',
  'We took the long way round because the bridge was closed.',
  'The train was ten minutes late this morning.',
  'I need to buy milk, eggs and bread on the way home.',
  'We watched a documentary about sharks last night.',
  'The meeting is moved to Thursday at two.',
  'I’m not sure what time the shop closes.',
  'I painted the fence on Saturday.',
  'She sent me the recipe for the soup.',
  'The kids have a swimming lesson after school.',
  'I walked the dog around the park twice.',
  'My brother is visiting next weekend.',
  'I finished the report and sent it to my manager.',
  'The weather is supposed to clear up by Friday.',
  'I booked the car in for a service.',
  'We planted tomatoes and some basil.',
  'I read two chapters before bed.',
  'The printer at work ran out of ink again.',
  'I cooked pasta for dinner.',
  'He asked if I could cover his shift on Tuesday.',
  'The library opens at nine on weekdays.',
  'I switched to a new phone plan.',
  'We talked about where to go for the summer.',
  'I fixed the leaking tap in the kitchen.',
  'My daughter starts at a new school in September.',
  'I spent the afternoon sorting old photos.',
  'The bus was packed so I walked.',
  'I picked up a parcel from the post office.',
  'We had a long chat about football.',
  'I signed up for a pottery class.'],
 warm:[
  'I felt safe and calm sitting by the sea.',
  'It was a really good day with the kids.',
  'I’m happy with how the garden looks this year.',
  'I slept well and woke up rested.',
  'I felt loved at the party.',
  'We laughed the whole way home.',
  'I feel confident about the interview tomorrow.',
  'My friend really listened to me today.',
  'I felt supported by my team this week.',
  'I’m proud of how far I’ve come.',
  'I feel hopeful about the new job.',
  'It was lovely to see everyone again.',
  'I feel at peace with the decision.',
  'She made me feel welcome straight away.',
  'I felt relaxed for the first time in ages.',
  'I’m grateful for my friends.',
  'The holiday was exactly what I needed.',
  'I finally feel like myself again.',
  'We had a lovely quiet evening in.',
  'I feel strong and clear today.'],
 trap:[
  'The coffee was too bitter so I added sugar.',
  'My phone battery was drained by lunchtime.',
  'I lost my keys again this morning.',
  'The dog was shaking off the water after the swim.',
  'I can’t wait for the holiday.',
  'The film had a sad ending but I loved it.',
  'The traffic was heavy on the motorway.',
  'I was tired after the long hike, in a good way.',
  'The pizza was so good I couldn’t stop eating it.',
  'The bread had gone hard so I made toast.',
  'We were stuck in traffic for twenty minutes.',
  'He’s down at the shops getting milk.',
  'The cat knocked a glass off the table and it broke.',
  'That plan is not safe for the old bridge, so we drove around.',
  'I haven’t heard back from the plumber yet.',
  'I haven’t seen that film yet.',
  'The kids were so wound up after the party.',
  'The match was a total wipeout for the other team.',
  'I was blue in the face from laughing.',
  'The cold snap killed off the tomato plants.',
  'The old printer finally died today.',
  'It was a heavy box but I managed.',
  'She was mad about the new puppy.',
  'The match was intense right to the end.',
  'I got a bit of a fright when the cat jumped out.',
  'We ran out of time before dessert.',
  'The tap was running cold all morning.',
  'Prices are crazy at the moment.',
  'I’m dying to see the new film.',
  'My legs were killing me after the run.']};

module.exports={PAIN:PAIN, QUIET:QUIET};
