/* WHAT EACH CANDIDATE ADDITION BUYS, measured over corpora that exist rather
   than over a labelled set that does not. Three corpora:
     book     117,716 words of the owner's own prose
     voices   the 14 persona says lines the product ships
     events   nothing. there is no corpus of real journal entries yet, and
              this file must not pretend otherwise. */
var path=require('path'), fs=require('fs');
var E=require(path.resolve(process.env.ENGINE||'engine.js'));
var SP='/tmp/claude-0/-home-user-MOB/e909b21c-7092-5fcd-af76-1092a869307f/scratchpad/';
var book=fs.readFileSync(SP+'book.txt','utf8');
var voices=E.PEOPLE.map(function(p){return p.says;});
var bwords=book.toLowerCase().replace(/[^a-z' ]+/g,' ').split(/\s+/).filter(Boolean);
var bw={};bwords.forEach(function(w){bw[w]=(bw[w]||0)+1;});
var vw={};voices.join(' ').toLowerCase().replace(/[^a-z' ]+/g,' ').split(/\s+/).forEach(function(w){if(w)vw[w]=1;});
console.log('corpora: book '+bwords.length+' tokens, '+Object.keys(bw).length
 +' forms; voices '+voices.length+' lines, '+Object.keys(vw).length+' forms');

/* --- CANDIDATE A: the axis words, derived from CHG2SEAT and CHG2FET --- */
var CHG2SEAT={fear:'root',anger:'solar',shame:'sacral',disgust:'sacral',apathy:'throat',
 shock:'eye',sadness:'heart',grief:'heart',surprise:'heart',anticipation:'solar',
 anxiety:'solar',pride:'crown',guilt:'sacral',craving:'sacral',separation:'crown'};
var axes=E.CHARGES.map(function(c){return c.toLowerCase();});
var cues={};E.SAB33.forEach(function(r){r[1].forEach(function(p){cues[p[0]]=1;});});
var want={};axes.concat(Object.keys(cues)).forEach(function(w){want[w]=1;});
var need=Object.keys(want).filter(function(w){return E.scanStory(w).length===0;});
console.log('\nCANDIDATE A, the canon words the instrument is built on');
console.log('  wanted        '+Object.keys(want).length+' distinct words (9 axis names + '+Object.keys(cues).length+' saboteur cues, overlapping)');
console.log('  missing now   '+need.length+'  '+JSON.stringify(need));
console.log('  in the book   '+need.filter(function(w){return bw[w];}).length+' of '+need.length
 +'  counts '+JSON.stringify(need.map(function(w){return w+':'+(bw[w]||0);})));
need.forEach(function(w){ if(!CHG2SEAT[w]) console.log('  NO SEAT for '+w+' in CHG2SEAT, so it cannot be derived'); });

/* --- CANDIDATE B: the fold, confirmed by corpus rather than generated freely --- */
var RULES=[
 ['s',   function(k){return !/(s|x|z|ch|sh|y)$/.test(k);},        function(k){return k+'s';}],
 ['es',  function(k){return /(s|x|z|ch|sh)$/.test(k);},           function(k){return k+'es';}],
 ['ies', function(k){return /[^aeiou]y$/.test(k);},               function(k){return k.slice(0,-1)+'ies';}],
 ['ed',  function(k){return /[^ey]$/.test(k)&&!/(ed|ing|ness)$/.test(k);},function(k){return k+'ed';}],
 ['d',   function(k){return /e$/.test(k);},                       function(k){return k+'d';}],
 ['ied', function(k){return /[^aeiou]y$/.test(k);},               function(k){return k.slice(0,-1)+'ied';}],
 ['ing', function(k){return /[^ey]$/.test(k)&&!/(ed|ing)$/.test(k);},function(k){return k+'ing';}],
 ['eing',function(k){return /e$/.test(k);},                       function(k){return k.slice(0,-1)+'ing';}],
 ['ped', function(k){return /[^aeiou][aeiou][pgmnt]$/.test(k);},  function(k){return k+k.slice(-1)+'ed';}],
 ['ping',function(k){return /[^aeiou][aeiou][pgmnt]$/.test(k);},  function(k){return k+k.slice(-1)+'ing';}],
 ['V',   function(k){return /[a-z]{3}ed$/.test(k);},              function(k){return k.slice(0,-2)+'ing';}],
 ['Vs',  function(k){return /[a-z]{3}ed$/.test(k);},              function(k){return k.slice(0,-2)+'s';}],
 ['Vy',  function(k){return /[a-z]{2}ied$/.test(k);},             function(k){return k.slice(0,-3)+'ying';}],
 ['ness',function(k){return /[a-z]{4}$/.test(k)&&!/(ness|ion|ity|ing|ed|s)$/.test(k);},function(k){return k+'ness';}]];
var single=Object.keys(E.LEX).filter(function(w){return w.indexOf(' ')<0;});
var gen={};
single.forEach(function(k){RULES.forEach(function(r){
 if(!r[1](k))return; var f=r[2](k);
 if(E.LEX[f]||gen[f])return; gen[f]={from:k,rule:r[0]};});});
var G=Object.keys(gen);
var inB=G.filter(function(f){return bw[f];}), inV=G.filter(function(f){return vw[f];});
var conf=G.filter(function(f){return bw[f]||vw[f];});
console.log('\nCANDIDATE B, the fold');
console.log('  generated by rule                '+G.length+' forms from '+single.length+' single word keys');
console.log('  confirmed by the book            '+inB.length);
console.log('  confirmed by the persona voices  '+inV.length+'  '+JSON.stringify(inV));
console.log('  confirmed by either              '+conf.length+', which is '
 +Math.round(100*conf.length/G.length)+' percent of what the rules generate');
console.log('  admitted forms:');
conf.sort().forEach(function(f){console.log('    '+(f+'                ').slice(0,16)
 +' from '+(gen[f].from+'            ').slice(0,13)+' rule '+(gen[f].rule+'    ').slice(0,5)
 +' book '+String(bw[f]||0).padStart(4)+(vw[f]?'  voices yes':''));});
