/* ============================================================
   THE HERO FIGURE, GENERATED FROM THE PRODUCT'S OWN TABLES.

   The avatar is the centrepiece, ruled in his words, and the landing page
   carried type and rules and nothing else. This draws the figure the Body
   page draws, off the same data: BODYPATH is the body outline, NERVEBR is
   the traced nerve map, SEATXY is where the seven seats sit on it, and PAL
   is their colours. All four come out of engine.js, so the figure cannot
   drift from the instrument the way a hand drawn one would.

   It is generated rather than scripted at run time because the landing page
   carries no engine. Half a megabyte of arithmetic on a page whose whole job
   is the first four seconds is the wrong trade, and a figure that needs a
   script is a figure that is missing when the script is.

       node funnel/make-figure.js

   It rewrites the block between the two markers in funnel/index.html and
   prints what changed. NO TEXT GOES INSIDE IT. The hero carries no text.
   ============================================================ */
var fs=require('fs'), path=require('path');
var here=__dirname;
var e=require(path.join(here,'..','engine.js'));

/* PMS, PMTX and PMTY are the transform that lands the body path inside the
   0 to 100 box the seats and the nerves are already expressed in. They are
   not on the engine's export list, so they are read out of the source they
   are declared in rather than copied here as three literals that would then
   be correct only until somebody moves the figure. */
var figSrc=fs.readFileSync(path.join(here,'..','atuned_src','engine','data','figure.js'),'utf8');
var m=figSrc.match(/var\s+PMS\s*=\s*([\d.]+)\s*,\s*PMTX\s*=\s*([-\d.]+)\s*,\s*PMTY\s*=\s*([-\d.]+)/);
if(!m)throw new Error('figure.js no longer declares PMS, PMTX and PMTY on one line');
var PMS=+m[1], PMTX=+m[2], PMTY=+m[3];

var SEATS=['root','sacral','solar','heart','throat','eye','crown'];
var VAR={root:'--root',sacral:'--sacral',solar:'--solar',heart:'--heart',
         throat:'--throat',eye:'--eye',crown:'--crown'};

function n(v,d){return (+v).toFixed(d==null?2:d);}

var out=[];
out.push('<svg class="hero" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet" aria-hidden="true">');

/* one radial gradient per seat, in that seat's own colour. the seats are not
   discs: charge is heat in tissue and heat has no edge, which is the ruling
   the Body page already carries. */
out.push(' <defs>');
SEATS.forEach(function(k){
 out.push('  <radialGradient id="hs-'+k+'">'
  +'<stop offset="0" stop-color="var('+VAR[k]+')" stop-opacity=".62"/>'
  +'<stop offset=".55" stop-color="var('+VAR[k]+')" stop-opacity=".18"/>'
  +'<stop offset="1" stop-color="var('+VAR[k]+')" stop-opacity="0"/>'
  +'</radialGradient>');});
out.push('  <clipPath id="heroClip"><path transform="translate('+PMTX+','+PMTY+') scale('+PMS
 +')" d="'+e.BODYPATH+'"/></clipPath>');
out.push(' </defs>');

/* the silhouette. a filled shape rather than a wire, so the field has a body
   to sit in. */
out.push(' <path class="hero-body" transform="translate('+PMTX+','+PMTY+') scale('+PMS+')" d="'
 +e.BODYPATH+'"/>');

/* the traced nerve map, clipped to the body, each branch in the colour of the
   seat it belongs to. */
out.push(' <g clip-path="url(#heroClip)" class="hero-nerves">');
e.NERVEBR.forEach(function(br){
 out.push('  <path d="M'+br.p.map(function(q){return n(q[0])+','+n(q[1]);}).join('L')
  +'" stroke="var('+(VAR[br.s]||'--accent')+')"/>');});
out.push(' </g>');

/* the seven seats, clipped to the body so the heat stays in the tissue. */
out.push(' <g clip-path="url(#heroClip)">');
SEATS.forEach(function(k){
 var s=e.SEATXY[k];
 if(!s)throw new Error('SEATXY has no seat called '+k);
 out.push('  <circle cx="'+n(s.x)+'" cy="'+n(s.y)+'" r="13" fill="url(#hs-'+k+')"/>');});
out.push(' </g>');

/* and the seat itself, a small ring. ring, not fill, and clipped to the body
   with everything else. SEATXY is a centroid of the marks that seat carries,
   not a point on the spine: the third eye's is at x 42.96, which is off the
   neck, and unclipped it drew a coloured ring floating in the air beside the
   figure. The table is the table and is not overridden here. A mark the table
   puts outside the body simply does not draw. */
out.push(' <g clip-path="url(#heroClip)">');
SEATS.forEach(function(k){
 var s=e.SEATXY[k];
 out.push('  <circle class="hero-seat" cx="'+n(s.x)+'" cy="'+n(s.y)
  +'" r="1.5" stroke="var('+VAR[k]+')"/>');});
out.push(' </g>');

out.push('</svg>');
var svg=out.join('\n');

var page=path.join(here,'index.html');
var html=fs.readFileSync(page,'utf8');
var A='<!-- FIGURE START. Generated by make-figure.js. Do not edit by hand. -->';
var B='<!-- FIGURE END -->';
var i=html.indexOf(A), j=html.indexOf(B);
if(i<0||j<0)throw new Error('index.html is missing the figure markers');
var before=html.slice(i+A.length,j);
html=html.slice(0,i+A.length)+'\n'+svg+'\n'+html.slice(j);
fs.writeFileSync(page,html);
console.log('figure: '+e.NERVEBR.length+' nerve branches, '+SEATS.length+' seats, '
 +svg.length+' bytes'+(before.trim()===svg?' (unchanged)':' (rewritten)'));
