
/* ============================================================
   The engine is DOM free. In a browser these are globals on the
   concatenated script. In node the same file is requireable, so the
   engine can be tested headlessly and shared with Atuned through the
   one profile object the schema contract defines.
   ============================================================ */
if(typeof module!=='undefined'&&module.exports){
 module.exports={
  /* data */      NODES:NODES, SAB_LIB:SAB_LIB, HCX_LIB:HCX_LIB, SAB33:SAB33, SAB_PI:SAB_PI, GATEGLYPH:GATEGLYPH,
                  APC:APC, APC_REL:APC_REL, APC_EMB:APC_EMB,
                  SABDEF:SABDEF, DOMDEF:DOMDEF, GLOSS:GLOSS, HARM:HARM,
  /* meter */    meterFirst:meterFirst,
  /* undo */     undoPush:undoPush, undoPop:undoPop, undoDepth:undoDepth,
                  undoPeek:undoPeek, undoClear:undoClear, UNDO_MAX:UNDO_MAX,
  /* avatar */   avatarBlank:avatarBlank, avatarValid:avatarValid, avatarDue:avatarDue,
                 avatarDaysLeft:avatarDaysLeft, avatarGap:avatarGap,
                 avatarProgress:avatarProgress, AV_MONTH:AV_MONTH,
  /* purpose */  purposeBlank:purposeBlank, purposeReady:purposeReady,
                 purposeCentre:purposeCentre, purposeRead:purposeRead,
                 boundaryCount:boundaryCount, boundaryCross:boundaryCross,
                 PUR_SIDES:PUR_SIDES, PUR_PER_SIDE:PUR_PER_SIDE,
                 PUR_SOUL:PUR_SOUL, PUR_EGO:PUR_EGO,
  /* plan */     PLANS:PLANS, PLAN_BY:PLAN_BY, PLAN_ALWAYS:PLAN_ALWAYS, SEE_ORDER:SEE_ORDER,
                 PLAN_LIVE:PLAN_LIVE, PLAN_DEAD:PLAN_DEAD,
                 planState:planState, planOf:planOf, planSees:planSees,
                 planNextSight:planNextSight, planAllowance:planAllowance,
                 planUpgrade:planUpgrade, RUN_MAX:RUN_MAX,
                 planYear:planYear, PLAN_YEAR_FREE:PLAN_YEAR_FREE,
                 planYear:planYear, PLAN_YEAR_FREE:PLAN_YEAR_FREE,
                 LEAD_SEES:LEAD_SEES, LEAD_HIDDEN:LEAD_HIDDEN, leadSees:leadSees,
                 EQUIV:EQUIV, EQUIV_NONE:EQUIV_NONE, equivOf:equivOf, planWorth:planWorth,
  /* ages */     AGES:AGES, AGE_TEST:AGE_TEST, AGE_LO:AGE_LO, AGE_HI:AGE_HI,
                 ageFinding:ageFinding, AGE_WORKED:AGE_WORKED,
  /* compass */  MIRROR:MIRROR, MASTERS:MASTERS, BLUEPRINT:BLUEPRINT, CIRCLES:CIRCLES,
                 CASCADE:CASCADE, DESCENT:DESCENT, DESCENT_REFER:DESCENT_REFER,
                 mirrorAt:mirrorAt, darkRead:darkRead, circleAt:circleAt,
                 DARK_MAL:DARK_MAL, DARK_CQ:DARK_CQ,
                 GOVERN:GOVERN, quadrant:quadrant, outwardShare:outwardShare, organisedShare:organisedShare, ORG_W:ORG_W,
                 FAM_OUT:FAM_OUT, FAM_IN:FAM_IN, GOV_ORG:GOV_ORG, GOV_MAL:GOV_MAL, GOV_ANGEL:GOV_ANGEL,
  /* labels */   TIERDEF:TIERDEF, TIER_BY:TIER_BY, tierOf:tierOf,
                 MEDIAN:MEDIAN, MEDIAN_LO:MEDIAN_LO, MEDIAN_HI:MEDIAN_HI,
                 medianRange:medianRange, tierTop:tierTop, tierRange:tierRange,
  /* astro */     julianDay:julianDay, sunLon:sunLon, moonLon:moonLon, gmst:gmst,
                  ascendant:ascendant, signOf:signOf, degInSign:degInSign,
                  gateOf:gateOf, designJD:designJD, birthJD:birthJD, PLACE:PLACE,
                  usDST:usDST, euDST:euDST, GATE_WHEEL:GATE_WHEEL, GATE_ARC:GATE_ARC,
                  chineseYear:chineseYear, spiritualOf:spiritualOf,
  /* catalog */   C3_VERB:C3_VERB, C3_STEM:C3_STEM, C3_TRUTH:C3_TRUTH, C3_GATE9:C3_GATE9,
                  C3_BAND:C3_BAND, C3_LADDER:C3_LADDER, C3_POLE:C3_POLE, C3_BILATERAL:C3_BILATERAL,
                  C3_CHAIN:C3_CHAIN, C3_DIR:C3_DIR, C3_PART:C3_PART, C3_HEAD:C3_HEAD,
                  C3_THEME:C3_THEME, C3_KIND:C3_KIND, C3_TRUTHRULE:C3_TRUTHRULE, C3_FAIL:C3_FAIL,
                  CARDSET:CARDSET, CARD_OPEN:CARD_OPEN, CARD_SHUT:CARD_SHUT, CARD_STEP:CARD_STEP,
                  AXCARD:AXCARD, AXC_UN:AXC_UN, CARD_BY:CARD_BY, AXC_BY:AXC_BY, AX_STEM:AX_STEM,
                  cardLine:cardLine, cardDepth:cardDepth, axLine:axLine, c3Band:c3Band,
                  HARM_AX:HARM_AX, KB_RENAME:KB_RENAME, KB_KEY:KB_KEY, INFER_NOUN:INFER_NOUN,
                  SABAUTH:SABAUTH, ARCH18:ARCH18, CHILD:CHILD, CHARGES:CHARGES,
                  DOMAINS:DOMAINS, ARCH:ARCH, SI:SI, SINAMES:SINAMES, MASKS:MASKS,
                  BANDS:BANDS, PAL:PAL, ROOTD:ROOTD, ROOTCOL:ROOTCOL, AFFIN:AFFIN,
                  PRACTICE:PRACTICE, EXPR:EXPR, PMBANDS:PMBANDS, FLOWSEAT:FLOWSEAT,
                  PAINREG:PAINREG, PEOPLE:PEOPLE, LAWSET:LAWSET, BIRTH:BIRTH,
                  LEX:LEX, ADJ2CHG:ADJ2CHG, PHRASES:PHRASES, VERP:VERP,
                  NERVEBR:NERVEBR, BODYPATH:BODYPATH, TAB:TAB,
  /* indexes */   W:W, BY:BY, ALL_SAB:ALL_SAB, S:S,
  /* soul */      buildSoul:buildSoul, affinity:affinity, bandIg:bandIg,
  /* engine */    compute:compute, suscAll:suscAll, balance:balance, OUTWARD:OUTWARD, INWARD:INWARD,
  /* seed */      TYPE16:TYPE16, SEED16:SEED16, seedAxes:seedAxes, seedApply:seedApply,
                  seedClear:seedClear, seedShare:seedShare, seedValid:seedValid, accuracy:accuracy, sab33Detect:sab33Detect,
                  sabLevels:sabLevels, exprFill:exprFill, exprRead:exprRead,
  /* gates */     verpScan:verpScan, verpApply:verpApply, verpFactor:verpFactor,
                  verpRead:verpRead, verpShare:verpShare,
                  leanScan:leanScan, leanApply:leanApply, leanRead:leanRead,
                  VERPMIX:VERPMIX, LEANMIX:LEANMIX,
  /* the door */  read:read, input:input, throughput:throughput, output:output,
                  gatesClear:gatesClear, gatesLoad:gatesLoad, gatesSave:gatesSave,
  /* schema */    blankProfile:blankProfile, loadProfile:loadProfile,
                  saveProfile:saveProfile, snapshot:snapshot,
                  pExport:pExport, pImport:pImport, validateProfile:validateProfile, importError:importError,
                  meterRun:meterRun, meterRead:meterRead, meterKey:meterKey,
                  meterNext:meterNext, meterPlan:meterPlan, LINES_PER_CH:LINES_PER_CH, MARKERS:MARKERS, markersFor:markersFor, PAT_PER_YEAR:PAT_PER_YEAR,
                  PAT_GEN:PAT_GEN, PAT_REF_AGE:PAT_REF_AGE,
                  profiles:function(){return PROFILES;}, current:function(){return CURP;}, SCHEMA_V:SCHEMA_V,
                  bindStore:bindStore, PKEY:PKEY, pPersist:pPersist, saveState:saveState,
                  storeBound:function(){return STORE_BOUND;},
  /* intake */    iqList:iqList, iqScore:iqScore, iqApply:iqApply,
  /* sniffer */   scanStory:scanStory, parseStory:parseStory, applyStory:applyStory,
                  pathOf:pathOf, seatOf:seatOf, SEATXY:SEATXY, PATHSEAT:PATHSEAT,
  /* birth */     sunSign:sunSign, moonSign:moonSign, risingSign:risingSign,
                  lifePath:lifePath, spiritual:spiritual, converge:converge,
                  /* the rest of the module. they were reachable as browser
                     globals but absent from the contract, so nothing outside
                     a page could test them. */
                  masterNumber:masterNumber, chineseElement:chineseElement,
                  hdOf:hdOf, geneKey:geneKey,
  /* util */      clamp:clamp, leaves:(typeof leaves==='function'?leaves:null)
 };
}
