/* The words on each page. Sentence case, no em dashes, mechanical and precise. */
module.exports={
 m1:{title:'Ridgeline',eyebrow:'Matrix, redesign 1 of 3, round OT',
  lede:'Nine bands, one per child fetter, laid across the nineteen domains. It keeps the matrix’s two axes and drops the cells: the Flow band’s wave, with the data as its height.',
  rail:'Left rail form, 264 px wide',
  cap:'<span class="k">What a person reads at a glance</span><b>Which fetters are loud, and in which domains.</b> Height is the charge held at that domain, colour is the root the domain belongs to, a gold ring is a pair that weighs 1.3 times. A bead rides each band, quicker where the fetter holds more.',
  fine:'Reads S.charge, the mean SQ of the addresses in each domain by fetter cell, DOMAIN, AFFIN. Motion: the Field’s 4.2 s wave, nine bands entering 70 ms apart.'},
 m2:{title:'Polar',eyebrow:'Matrix, redesign 2 of 3, round OT',
  lede:'The matrix drawn on the Field’s own circle. Nine rings for the nine fetters, nineteen sectors for the domains, so a cell sits where its addresses sit on the wheel.',
  rail:'Left rail form, 264 px wide',
  cap:'<span class="k">What a person reads at a glance</span><b>Where on the wheel each fetter lives.</b> A thick, bright arc is a cell holding charge; the beads on it are the real addresses at their real slot angles. The outer band is the domains by root, thicker where the blueprint reaches further. Gold hairlines are the 1.3x pairs.',
  fine:'Reads W[108] (slot, fetter, SQ), DOMAIN, AFFIN, CQ. Motion: a light sweeps the wheel once in 14 s, arcs ride a radial wave, rings enter ring by ring.'},
 m3:{title:'Loom',eyebrow:'Matrix, redesign 3 of 3, round OT',
  lede:'The grid is kept and set under tension. Nineteen domain threads cross nine fetter threads; where they meet there is a ring, and a charged ring plucks both threads.',
  rail:'Left rail form, 264 px wide',
  cap:'<span class="k">What a person reads at a glance</span><b>Where the grid is pulled.</b> A ring grows with the charge in that cell and the two threads through it shiver. Light runs along a row quicker where the fetter holds more, and down a column quicker where the blueprint reaches more.',
  fine:'Reads the 9 by 19 cell table from W, S.charge, DOMAIN, AFFIN. Motion: threads draw in 60 ms apart, nodes land with one overshoot, then the 4.2 s pluck.'},
 g1:{tall:true,title:'Meshing gears',eyebrow:'Fetters and the celestial layer, picture 1 of 3, round OT',
  lede:'Three gears with the product’s own tooth counts: the sky has 12 signs, the roots are 4, the fetters are 9. Turn it by hand and the other two follow.',
  rail:null,
  cap:'<span class="k">What a person reads at a glance</span><b>The sky and the fetters share a register.</b> The 12 to 4 mesh is exact: signs repeat their element every fourth tooth, so Aries, Leo and Sagittarius always meet the same root tooth. The thin lines are the product’s only real link: element to root, root to its affine fetters.',
  fine:'Honest limit: the rotation is not a force. The sky does not turn the fetters. The lines are the claim; the gears are the register.'},
 g2:{title:'Nested rings',eyebrow:'Fetters and the celestial layer, picture 2 of 3, round OT',
  lede:'Five rings that turn at their own rates, set by their own counts. The sky is the outer ring; the roots and the fetters ride together beneath it; the domains are inside.',
  rail:null,
  cap:'<span class="k">What a person reads at a glance</span><b>Which sky points lean on which fetters.</b> Each sky point sends a thread to the root its element reads as, and that root’s fetters sit directly beneath it. A solid thread means the person’s own domains run that root; a dashed one means the sky reads one way and the person runs another.',
  fine:'Drag the outer ring and the inner rings follow late, like friction. That lag is animation, not a claim. Chords inside the outer ring are real aspects between sky points.'},
 g3:{tall:true,title:'Layered tower',eyebrow:'Fetters and the celestial layer, picture 3 of 3, round OT',
  lede:'Five discs, one above the next, each turning on its own axis. The sky sits on top and the 108 addresses sit at the foot, with the fetters and domains between.',
  rail:null,
  cap:'<span class="k">What a person reads at a glance</span><b>What sits above what.</b> Light drops from each sky point through its root to the fetters under it, and from the fetters down to the addresses that carry their charge. Read top to bottom it is the product’s own chain: sky, root, fetter, address.',
  fine:'Each disc is an ellipse, so the whole tower is canvas 2D and no 3D engine. Layers are strata, not a mechanism: nothing here says a lower disc is turned by a higher one.'}
};
