"""Write atuned_src/engine/data/zones.js from the time zone database's own
table of representative points, so the coordinates Rising reads are the
published ones and can be regenerated and compared rather than trusted.

    python3 tools/zonetab.py                       reads /usr/share/zoneinfo
    python3 tools/zonetab.py path/to/zone.tab      reads a given copy
    python3 tools/zonetab.py --check               exits 1 if the carried table
                                                   differs from the source

zone.tab and not zone1970.tab, measured. zone1970.tab merges every zone whose
clocks have agreed since 1970 and keeps the most populous city, so Norway,
Sweden and Denmark all read Berlin's horizon, 312 rows. zone.tab keeps one row
per country and zone, 418 rows, which is the same list Intl offers a person in
the time zone field, so the name they pick is the row they get."""
import os, re, sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT = os.path.join(ROOT, 'atuned_src', 'engine', 'data', 'zones.js')
SRC = '/usr/share/zoneinfo/zone.tab'
ISO6709 = re.compile(r'^[+-]\d{4}(\d{2})?[+-]\d{5}(\d{2})?$')


def rows(path):
    """(zone name, ISO 6709 point) for every data row, exactly as published."""
    with open(path, encoding='ascii') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            cols = line.rstrip('\n').split('\t')
            # a malformed row is a reason to stop, not a row to skip: a table
            # quietly missing a zone is a Rising quietly missing for somebody
            if len(cols) < 3 or not ISO6709.match(cols[1]):
                raise ValueError('unreadable row in %s: %r' % (path, line))
            yield cols[2], cols[1]


def version(path):
    """The tzdata release the table came from, read off tzdata.zi beside it."""
    zi = os.path.join(os.path.dirname(path), 'tzdata.zi')
    try:
        with open(zi, encoding='ascii') as f:
            m = re.match(r'# version (\S+)', f.readline())
            return m.group(1) if m else 'unknown'
    except OSError:
        return 'unknown'


def render(path):
    groups = {}
    for name, pt in rows(path):
        region, _, rest = name.partition('/')
        groups.setdefault(region, []).append(rest + pt)
    body = ',\n'.join(" %s:'%s'" % (r, ' '.join(sorted(v))) for r, v in sorted(groups.items()))
    n = sum(len(v) for v in groups.values())
    return HEAD % {'ver': version(path), 'n': n} + 'const ZONEPT={\n' + body + '};\n'


HEAD = '''
/* ============================================================
   ZONES. One representative point per time zone, for the horizon.
   GENERATED by tools/zonetab.py from zone.tab, tzdata %(ver)s,
   %(n)d rows. Do not edit by hand: regenerate, and the engine gate
   compares this against the machine's own copy where it has one.

   Rising needs where the horizon was, and a time zone only says what
   the clock read, so a person born outside the nine PLACE cities got
   no ascendant at all. Ruled 26 September, in his words: "I don't need
   every city, I just need what are the slices in the time zone." The
   time zone database publishes exactly that, the principal location
   of every zone, public domain, and this is it verbatim: the point is
   ISO 6709, degrees and minutes and sometimes seconds, latitude first,
   north and east positive. Grouped by region only to carry each
   region name once.

   It is a nearer horizon than none and it is not the person's own.
   America/Los_Angeles is Los Angeles for Portland too.
   ============================================================ */
'''

if __name__ == '__main__':
    args = [a for a in sys.argv[1:] if a != '--check']
    src = args[0] if args else SRC
    text = render(src)
    if '--check' in sys.argv:
        with open(OUT, encoding='utf-8') as f:
            same = f.read() == text
        print('zones.js matches %s' % src if same else 'zones.js DIFFERS from %s' % src)
        sys.exit(0 if same else 1)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(text)
    print('wrote %s, %d bytes' % (os.path.relpath(OUT, ROOT), len(text.encode('utf-8'))))
