/* make-index.js. Writes mockups/onboarding/index.html, the contact sheet.
   Run from the repo root after build.js:  node mockups/onboarding/make-index.js
   Every figure on the sheet is either measured (and the run is named) or is
   marked Judgement. Copy is tagged TDD, owner, storyboard or PROPOSED. */
var fs=require('fs'),path=require('path');
var root=__dirname;
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function tags(c){return (c||[]).map(function(t){return '<span class="tg '+t.split(' ')[0].toLowerCase()+'">'+esc(t)+'</span>';}).join('');}
function card(f){
 var live=f.live?'<a href="'+f.live+'">Open live</a>':'';
 return '<article class="card" id="'+f.id+'"><header><span class="no">'+esc(f.no)+'</span><h3>'+esc(f.title)+'</h3>'+live+'</header>'
  +'<div class="shots"><a href="png/'+f.png+'-1600.png"><img loading="lazy" src="png/'+f.png+'-1600.png" alt="'+esc(f.title)+' at 1600 by 1000"></a>'
  +'<a href="png/'+f.png+'-390.png"><img loading="lazy" src="png/'+f.png+'-390.png" alt="'+esc(f.title)+' at 390 by 844"></a></div>'
  +'<dl><dt>At a glance</dt><dd>'+f.glance+'</dd><dt>Costs the person</dt><dd>'+f.person+'</dd><dt>Costs to build</dt><dd>'+f.build+'</dd></dl>'
  +'<div class="tgs">'+tags(f.copy)+'</div></article>';}
function states(d,list){
 return '<div class="srow">'+list.map(function(s){return '<figure><a href="png/login-'+d+'-'+s[0]+'-1600.png"><img loading="lazy" src="png/login-'+d+'-'+s[0]+'-1600.png" alt="Login '+d.toUpperCase()+' '+s[0]+'"></a><a class="ph" href="png/login-'+d+'-'+s[0]+'-390.png"><img loading="lazy" src="png/login-'+d+'-'+s[0]+'-390.png" alt="Login '+d.toUpperCase()+' '+s[0]+' at 390"></a><figcaption><b>'+s[1]+'</b><span>'+s[2]+'</span></figcaption></figure>';}).join('')+'</div>';}

var login=[
 {d:'a',name:'A. The ring',live:'login-a.html',
  line:'The boot’s own ring, with the form inside it. This is the owner’s round MH ruling kept: the login sits on the Atuned animation screen and the first paint is the animation itself.',
  glance:'A dial with one name on it. Two fields, one big button, a small Guest. The ring is waiting for you.',
  person:'About 10 seconds (Judgement): one name, one passphrase, one press. No email anywhere on the sign in.',
  build:'Cheapest to wire into what exists: the 112 ticks and the arcs are the Field’s own, and the boot ring becomes this ground, so the 5.4 second boot overture stops being a separate screen. New work is two SVG paths for the connect line.',
  grammar:'Username typed: a node appears at the top (signal). Passphrase typed: a path forms down both sides (connect). Log in: the ring closes and every tick reads full (confirm). Mismatch: the path stops and splits into two dashed branches with one alarm marker (contradiction). Alarm red is used on that marker and that sentence only.',
  st:[['signin','Empty','Nothing typed. The ring breathes, which means waiting.'],['filled','Typing','Name placed, path forming as the passphrase grows.'],['create','Create account','Username is free. The name is the only identity asked for.'],['error','Mismatch','The path splits. The sentence does not say which half was wrong.'],['dev','Developer options','Lower right, small, closed until pressed.'],['confirm','Confirm','Ring closed. This is the frame before the zoom into the Field.']]},
 {d:'b',name:'B. The bands',live:'login-b.html',
  line:'Seven waves, one per seat, with the form on a plate. Typing moves the two waves that mean something here.',
  glance:'A calm instrument. A large sentence, seven coloured lines, a plate. It reads as a place before it reads as a form.',
  person:'About 10 seconds (Judgement). Same fields as A. The waves give the most feedback of the three, which is a cost to attention: they move while you type.',
  build:'Waves are seven redrawn paths, about 60 lines of script. Cheap, but it runs a frame loop while the page is open, so it needs the reduced motion path (drawn, built in) and a pause when the tab is hidden (not drawn).',
  grammar:'Username lifts the Throat wave (the name is said aloud). Passphrase lifts the Root wave (ground). Log in flattens all seven into parallel lines (settle). Mismatch puts the Root wave out of phase and ends it on an alarm marker. The seat pairing is PROPOSED.',
  st:[['signin','Empty','Seven quiet waves.'],['filled','Typing','Throat and Root lifted and named at their ends.'],['create','Create account','Same plate, one line of help under the passphrase.'],['error','Mismatch','Root wave out of phase, one alarm marker.'],['dev','Developer options','Same corner, same size as A and C.'],['confirm','Confirm','All seven lines flat and parallel.']]},
 {d:'c',name:'C. The address grid',live:'login-c.html',
  line:'112 nodes, 16 to a seat. The form sits on one row above them. Typed characters light nodes in two rows.',
  glance:'A sentence, one row to fill in, and a field of small rings. The most like a lab instrument and the least like a login page.',
  person:'About 10 seconds (Judgement). Two fields and a button share one row at 1600, which is the shortest path of the three. At 390 it stacks.',
  build:'Lowest of the three: 112 small circles and two lit rows. It loses the ring, so it shares nothing with the boot and the 5.4 second overture would stay a separate screen.',
  grammar:'Each character in the username lights a node in the Throat row. Each in the passphrase lights a node in the Root row, so the nodes work as the password dots do. Log in lights every node. Mismatch puts one alarm ring on the last Root node. Seat pairing PROPOSED.',
  st:[['signin','Empty','112 quiet rings, seat names at the left.'],['filled','Typing','Two rows lit, one node per character.'],['create','Create account','Name free, button reads Create account.'],['error','Mismatch','One alarm ring at the end of the Root row.'],['dev','Developer options','Open over the lowest rows.'],['confirm','Confirm','All 112 lit.']]}];

var onb=[
 {no:'O1',id:'o1',title:'Starting point, nothing picked',png:'onb-01-start',live:'onboarding.html#start',glance:'Twelve symbols on a ring, eleven named and one open door. One question. Nothing is selected, the middle waits.',person:'One tap. About 5 seconds (Judgement). No typing.',build:'Twelve ring icons in one family, drawn here. Round PB: twelve is the main version. Pain came in at his word in round PA and Fatigue went out to make room, because Burnout already names the long tired kind and Pain names the bodily one. The owner’s storyboard 02 had six symbols and an “I’ll tell you” door; the next frame says how to find out whether twelve is too many.',copy:['TDD What brought you here?','owner Pain','PROPOSED Fatigue out, to hold twelve','PROPOSED Pick the closest one.']},
 {no:'O1b',id:'o1b',title:'Is twelve too many, a note',png:'onb-01b-start-measure',live:'onboarding.html#start-measure',glance:'The twelve on a ring, and three readings that answer the question: choice time, drop at the page, and the share who pick Something else.',person:'Nothing. This is a note for the owner and the team, not a screen for a person.',build:'The product reports nothing about how it is used, and the privacy policy says so (section 3). So none of the three can be counted inside the product today. Watch five people with a stopwatch, or ask each person for a yes to a count they can see, and change the policy first. Every threshold on the frame is PROPOSED and is replaced by the first measured week. Slow and leaving is too many. Fast and choosing Something else is the wrong twelve. They have different cures.',copy:['PROPOSED median choice time past 10 seconds','PROPOSED Something else over 20 percent or under 3 percent','PROPOSED about 900 people on each side to compare twelve with six']},
 {no:'O2',id:'o2',title:'Starting point, picked',png:'onb-02-start-picked',live:'onboarding.html#start-picked',glance:'One symbol stays lit, the rest quiet down, a path runs to the ring and one seat sector lights, named.',person:'One more press, Begin. The 100 patterns line appears before any account exists.',build:'The seat each symbol lights is PROPOSED. The engine has no table from a starting point to a seat or an address (review of the TDD, question 3). That table is authored content, twelve rows.',copy:['TDD Your first 100 patterns are ready.','PROPOSED seat per symbol']},
 {no:'O3',id:'o3',title:'Feeling',png:'onb-03-feeling',live:'onboarding.html#feeling',glance:'A short answer box on the left. On the right the Field already holds your starting point and two words you typed.',person:'About 15 to 30 seconds (Judgement), one line of typing.',build:'The two word nodes need the word table to run on a short line. The review ranks three prompts in a row as a drop off risk (rank 2). Folding this into the next frame is an option and costs nothing to draw.',copy:['TDD What are you feeling today?','TDD How does that feeling run through you?','TDD Feel','PROPOSED Starting point chip']},
 {no:'O4',id:'o4',title:'Story, typing',png:'onb-04-story',live:'onboarding.html#story',glance:'Your sentence with the words that registered underlined in their seat colours, and the same words as nodes joined by lines.',person:'30 to 90 seconds of typing (Judgement, from the 45 to 90 second figure in DESIGN-firstrun). Nothing leaves the device.',build:'The underline layer exists in the Story tab. The field panel is new drawing. Measured by the review: the sniffer found nothing for 5 of 12 plain one line stories, which is why frame O10 exists.',copy:['TDD Tell us what’s off.','product Typing stays on this device. (from the mic tooltip)']},
 {no:'O5',id:'o5',title:'Story, speaking',png:'onb-05-story-voice',live:'onboarding.html#story-voice',glance:'The same screen with a live line that moves with your voice and a Listening state. The last words are dim until they settle.',person:'Same as typing, with a stop button. The disclosure line is in plain words and is shown before anything is recorded.',build:'The voice path uses the browser’s speech service. It refuses on a page opened from a file and the audio leaves the device (review, row 12). Needs a secure page.',copy:['TDD text and voice','product Recording sends the audio to your browser’s speech service. Typing does not leave this device.']},
 {no:'O6',id:'o6',title:'Mirror forming, one frame',png:'onb-06-forming',live:'onboarding.html#forming',glance:'Words become nodes, nodes join, the pattern gathers, then it finds a place on the body. This still is stage four of six.',person:'About 7 seconds of watching (Judgement). No input.',build:'Pure drawing, no new data. The full six stage strip is below. Every move is one of the TDD’s own grammar words.',copy:['TDD signal, notice, connect, pattern, mirror','PROPOSED Reading what you wrote']},
 {no:'O7',id:'o7',title:'Mirror',png:'onb-07-mirror',live:'onboarding.html#mirror',glance:'Your words on the left, what was noticed in the middle with the body and the pattern, the test on the right. Three kinds of statement, drawn three ways: a rule, a ring, a dashed edge.',person:'Read for 10 to 20 seconds (Judgement), one tap. The pattern contracts and releases on a slow loop: that is the animation the TDD asks for.',build:'The biggest frame. Quality, intensity, where and colour come from the sniffer. Cause and relationships do not (review row 13). The cause line here is the TDD’s example and is drawn as a hypothesis, not a fact, which answers review question 4 option A in layout only.',copy:['TDD Story tag, snippet, quality, intensity, cause, body location','TDD Does this feel accurate?','TDD That’s it, Not quite, Adjust','storyboard You said, Atuned noticed, Let’s test']},
 {no:'O8',id:'o8',title:'Not quite',png:'onb-08-mirror-notquite',live:'onboarding.html#mirror-notquite',glance:'The path splits in two with both ends open. Four chips ask which part was wrong.',person:'One tap, then a new reading. Rejection is treated as an answer, as the TDD says.',build:'PROPOSED. The TDD gives Not quite no next state (review, gap 3). This is one way to give it one. Needs a record type for a rejected reading.',copy:['PROPOSED Which part is off?','PROPOSED the four chips','storyboard Show another reading (storyboard 05)']},
 {no:'O9',id:'o9',title:'Adjust',png:'onb-09-mirror-adjust',live:'onboarding.html#mirror-adjust',glance:'What we read is held above, your correction goes below, and the Field redraws with the new path.',person:'Typing or speaking again, about 20 seconds (Judgement).',build:'SOURCE OS has to reinterpret the correction (TDD 18). With no language model that is the word table again on the new text; the cause line then stays the person’s own words.',copy:['TDD Tell us what’s off.','PROPOSED What we read','PROPOSED Update the reading']},
 {no:'O10',id:'o10',title:'Nothing came up',png:'onb-10-mirror-empty',live:'onboarding.html#mirror-empty',glance:'A question, not a verdict. The body with four seats ringed as choices.',person:'One tap. This is the frame for the person with something they cannot say, the one the TDD says arrives.',build:'Measured by the review: 5 of 12 plain stories read as nothing. Without this frame those people hit a blank Mirror. Needs the body as a picker, which the Body tab already draws.',copy:['storyboard When you think about it, where do you feel it?','storyboard Chest, Throat, Gut, Head, Somewhere else','PROPOSED Nothing came up from that']},
 {no:'O11',id:'o11',title:'Somatic setup',png:'onb-11-somatic',live:'onboarding.html#somatic',glance:'Your sentence held beside the body with one seat pulsing. Six things you might notice, one of them nothing.',person:'About 20 seconds to read (Judgement), then Begin. A Stop control sits beside it.',build:'The TDD line “Welcome to a somatic experience.” fails the voice gate (preamble) and is left off the screen; the owner decides. Stop is PROPOSED and is the one safety control: the review flags that the TDD has none (Ana, edge case).',copy:['TDD Turn your senses inward.','TDD Pressure, Density, Relief, Movement, Activation, Nothing','TDD no required sensation','PROPOSED Stop']},
 {no:'O12',id:'o12',title:'Mini release, in motion',png:'onb-12-release',live:'onboarding.html#release',glance:'One cluster of nodes and one word, large, naming the state. A path of six stops shows where you are. This still is Releasing.',person:'The TDD says short and linear. Length is open: the smallest run the engine makes is 4 lines, so the TDD’s “approximately 10” is not a size it produces. 8 or 12 fit (review, gap 9).',build:'Six parameter sets for one drawing, tweened. The release sentence is the TDD’s, which differs from the ruled one (“letting go”, six verbs) and is a placeholder. Frame strip below.',copy:['TDD I am releasing believing, thinking, feeling, behaving, acting.','TDD Held, Contracted, Releasing, Opening, Settling, Observing','PROPOSED Pattern 4 of 10 and the six one line descriptions']},
 {no:'O13',id:'o13',title:'After the release',png:'onb-13-observe',live:'onboarding.html#observe',glance:'Your cluster, now and as it was, side by side. Five ways to say what is here. Nothing asks for a score.',person:'One tap. About 5 seconds (Judgement).',build:'The five answers are the owner’s storyboard 11. The line under them keeps a feeling from being recorded as proof of change, which storyboard 11 asks for.',copy:['TDD Feel, reflect','storyboard I feel different, I see it differently, Something moved, Nothing changed, I’m not sure','PROPOSED What is here now?']},
 {no:'O14',id:'o14',title:'Handoff',png:'onb-14-handoff',live:'onboarding.html#handoff',glance:'Five nodes on one path, left to right, each holding what you did. Below it the loop as a ring with Discover lit.',person:'About 10 seconds to read (Judgement). One button, Open the Field. A second, quieter one for guests to keep the work.',build:'The five lines are the TDD’s, in sentence case, drawn as a path and not a list. The loop is a ring, never a column, per the standing ruling. The five nodes are the same five that fill in along the top of every earlier frame.',copy:['TDD You said, Atuned noticed, You tested, You worked with it, You observed','PROPOSED You did that.','PROPOSED Keep this: choose a username']}];

var tut=[
 {no:'T1',id:'t1',title:'The loop, with what you did on it',png:'tut-01-loop',live:'tutorial.html#t0',glance:'A ring with four stations. Discover and Flow are closed. Play is next.',person:'One press. Shows before it explains.',build:'The ring is the only progress object, docked small at the top right on every later frame. No step dots.',copy:['owner discover, play, flow, embody','PROPOSED Two done. Play is next.']},
 {no:'T2',id:'t2',title:'Play: the app opens an address',png:'tut-02-play',live:'tutorial.html#t1',glance:'A wheel of seven seats with a ghost pointer on one of them. The address opens beside it.',person:'No input needed. The pointer is drawn still here; in a build it would move to the seat and tap by itself, then the card opens.',build:'Needs the Field’s address card. The demonstration would be a scripted pointer, about 2 seconds.',copy:['DESIGN-firstrun Open one. Your words landed here.']},
 {no:'T3',id:'t3',title:'Flow: run it again',png:'tut-03-flow',live:'tutorial.html#t2',glance:'The cluster you released, and three figures: opened, left, rerun. Rerun is 0.',person:'One press to try a rerun, one to go on.',build:'The arithmetic is the engine’s: a rerun of opened ground costs nothing, the gift is 100. The 10 and the 90 assume a ten pattern release, which is open.',copy:['TDD reruns cost zero','PROPOSED Run it again.']},
 {no:'T4',id:'t4',title:'Embody: pick when',png:'tut-04-embody',live:'tutorial.html#t3',glance:'Three anchors to pick from and a day drawn as a path with one node placed.',person:'One tap and Save. About 10 seconds (Judgement).',build:'The Ritual When row already exists. The third anchor is PROPOSED. This is also where a push permission would be asked once accounts exist.',copy:['DESIGN-firstrun Pick when you will come back to it.','DESIGN-firstrun after I put the kettle on, before the first run of the day','PROPOSED when I notice it start']},
 {no:'T5',id:'t5',title:'The loop closes into the Field',png:'tut-05-landing',live:'tutorial.html#t4',glance:'The ring closes at the centre of the wheel. One main button, and a quieter one for the questions.',person:'One press. The ten questions are offered, never required.',build:'The closing line is the Help sheet’s own sentence from DESIGN-firstrun.',copy:['DESIGN-firstrun The wheel is your field. Left is what you are made of. Right is what it reads.','PROPOSED You closed the first turn.']},
 {no:'Q0',id:'q0',title:'Questions, the setup',png:'tut-q0-intro',live:'tutorial.html#q0',glance:'A scale from 0 to 10 with 5 marked, inside a ring of 21 quiet nodes, one per law. The ten that come first are drawn larger, the eleven that wait are faint. Skip is always at the top. See the laws opens the list.',person:'About 15 seconds to read (Judgement). Come back later is a first class button.',build:'The TDD’s sentence “Most people operate somewhere in the middle” is replaced with the owner’s own band wording, and “operate” is replaced because it fails the plain words gate. The ring of 21 builds up from nothing, as ruled.',copy:['TDD Reflect on a real moment','TDD 0 almost never, 5 half, 10 consistently','owner Five is the middle. Four to six is oscillating.']},
 {no:'Q1',id:'q1',title:'One integrity question, Truth',png:'tut-q1-integrity',live:'tutorial.html#q1',glance:'Question 7 of 10. One symbol for the law, one real moment, one continuum. The mark lands on the ring and nothing changes colour.',person:'One drag or tap, about 8 seconds each (Judgement). A high answer and a low answer look the same on purpose.',build:'The wording is PROPOSED. The scale direction matters: the TDD scores consistency, the funnel scores how often a fault happens, the Intake asks how often you do the virtue (review, section b4).',copy:['PROPOSED the question','TDD the scale meanings']},
 {no:'Q2',id:'q2',title:'The dilemma format',png:'tut-q2-dilemma',live:'tutorial.html#q2',glance:'Two poles, Choose a side and Break it up, and a middle that says Both.',person:'One drag. No score, no word like good or bad.',build:'The owner’s own example, round JQ. Non-harm is a Root law and is not among his ten, so this frame stays as the example of the format and carries no question number. The format is not ruled; the review lists three formats on the table.',copy:['owner You see two kids fighting. Do you choose a side, or break it up?']},
 {no:'Q3',id:'q3',title:'An archetype question',png:'tut-q3-archetype',live:'tutorial.html#q3',glance:'Two grey symbols, one a little warmer than the other, and a continuum between the two behaviours.',person:'One drag. Both is a real answer.',build:'The two icons here are stand ins for the existing archetype icon set. Saturation starts neutral and moves a little, as the TDD asks, and the line under it says it tracks a tendency.',copy:['TDD When something needs to change, do you tend to: Act immediately / Understand it deeply first','PROPOSED This tracks a tendency. It is not who you are.']}];

var ten=[
 {no:'QL',id:'ql',title:'The laws list, ten numbered',png:'tut-laws',live:'tutorial.html#laws',glance:'All 21 laws in seven columns, one per seat, bottom of the body at the left. Each wears its own mark from the engine’s table. The ten that come first carry a number from 1 to 10. The eleven that wait are faint.',person:'About 20 seconds to read (Judgement). Nobody has to read it: the route is See the laws, from the setup.',build:'The laws, their seats and their marks are read out of canon.js at build time, so the list cannot drift from the engine. The order is the body from the bottom to the top: Patience, Temperance, Duty, Accountability, Compassion, Forgiveness, Truth, Transparency, Humility, Unity. It opens on the quietest law and closes on the widest. Duty before Accountability is the engine’s own order inside the Solar seat.',copy:['owner the ten: Truth, Transparency, Unity, Humility, Compassion, Duty, Accountability, Patience, Temperance, Forgiveness','PROPOSED the order, by seat','PROPOSED Twenty one laws. You start with ten.']},
 {no:'Q4',id:'q4',title:'Patience, a real moment',png:'tut-q-patience-real',live:'tutorial.html#pat-r',glance:'Question 1 of 10. The hourglass in its Root red, one act, and a scale from 0 to 10.',person:'One drag, about 8 seconds (Judgement). A 4 and a 9 look the same on purpose.',build:'Wording PROPOSED. It names the act and the cost together: the wait is the cost.',copy:['PROPOSED Something you want is taking longer than you planned. You let it take that long.']},
 {no:'Q5',id:'q5',title:'Patience, a dilemma',png:'tut-q-patience-dilemma',live:'tutorial.html#pat-d',glance:'Two acts, Take it over and Wait for them, a middle that says Both, and a mark between.',person:'One drag. Neither pole is the answer. Taking it over can be care.',build:'Wording PROPOSED. The virtue sits on the right here. In the next dilemma it sits on the left, on purpose.',copy:['PROPOSED Someone you depend on is late with something you need today. Do you take it over, or wait for them?']},
 {no:'Q6',id:'q6',title:'Accountability, a real moment',png:'tut-q-accountability-real',live:'tutorial.html#acc-r',glance:'Question 4 of 10. The tally mark in Solar yellow, one act, a scale.',person:'One drag, about 8 seconds (Judgement).',build:'Wording PROPOSED. “Before anyone asks” is the part that separates the law from being caught.',copy:['PROPOSED Something went wrong and part of it was yours. You say so before anyone asks.']},
 {no:'Q7',id:'q7',title:'Accountability, a dilemma',png:'tut-q-accountability-dilemma',live:'tutorial.html#acc-d',glance:'Two acts, Say it was mine and Let it stand, the mark leaning to the left.',person:'One drag. Letting it stand is a real answer, and the frame does not call it a fault.',build:'Wording PROPOSED. The virtue sits on the left here.',copy:['PROPOSED A mistake of yours is being blamed on someone else. Do you say it was yours, or let it stand?']},
 {no:'Q8',id:'q8',title:'Compassion, a real moment',png:'tut-q-compassion-real',live:'tutorial.html#com-r',glance:'Question 5 of 10. The Heart mark in green, one act, a scale.',person:'One drag, about 8 seconds (Judgement).',build:'Wording PROPOSED. “You cannot fix it” keeps compassion apart from rescue.',copy:['PROPOSED Somebody near you is hurting, and you cannot fix it. You stay with them anyway.']},
 {no:'Q9',id:'q9',title:'Compassion, a dilemma',png:'tut-q-compassion-dilemma',live:'tutorial.html#com-d',glance:'Two acts, Walk on and Give him some, and a mark between, a little toward walking on.',person:'One drag. Both is a real answer.',build:'The owner’s own example, round JQ: a man on the street, give money or walk on. The virtue sits on the right here.',copy:['owner You see a beggar on the street, do you walk over them or give them money?','PROPOSED You pass a man asking for money. Do you give him some, or walk on?']}];

var base=[
 ['baseline/02-login-1600.png','baseline/02-login-390.png','Login today','The app is visible and dimmed behind a modal card. Email first. “Continue without an account” is the longest label on the card. Developer options sits bottom left of the card. Input border is 1.5 to 1 against its ground.'],
 ['baseline/04-onboarding-0-1600.png','baseline/04-onboarding-0-390.png','Onboarding today','A grey card over the same dimmed app. 372 words over four screens at the last measurement.'],
 ['baseline/04-onboarding-2-1600.png','baseline/04-onboarding-2-390.png','Signal test today','Text first, a disabled Next. The first thing a person does is read.'],
 ['baseline/06-tutorial-1-1600.png','baseline/06-tutorial-1-390.png','Tutorial today','A card that describes the result. It does not show it.'],
 ['baseline/07-funnel-index-1600.png','baseline/07-funnel-index-390.png','Funnel front page today','A long explanation, with a figure. The review marks this as the documentation first shape the TDD rules out.']];

var html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Onboarding mockups</title><style>'
+':root{--bg:#0C0D12;--panel:#1A1D26;--ink:#EFEDE8;--mid:#B4B0A8;--dim:#94908A;--edge:rgba(255,255,255,.12);--acc:#7EB8D4;--sans:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}'
+'*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:var(--sans);line-height:1.5;font-size:16px}'
+'a{color:var(--acc)}img{display:block;max-width:100%;height:auto;border-radius:10px;border:1px solid var(--edge)}'
+'.wrap{max-width:1500px;margin:0 auto;padding:40px 24px 80px}'
+'h1{font-size:40px;font-weight:500;letter-spacing:-.025em;margin:0 0 6px}h2{font-size:28px;font-weight:500;letter-spacing:-.02em;margin:64px 0 8px;padding-top:24px;border-top:1px solid var(--edge)}h3{font-size:19px;margin:0;font-weight:600}'
+'.lead{color:var(--mid);max-width:80ch;margin:6px 0}.small{color:var(--dim);font-size:14px}p{max-width:86ch}'
+'nav{display:flex;flex-wrap:wrap;gap:8px 18px;margin:20px 0 6px}nav a{font-size:14px}'
+'.key{display:flex;flex-wrap:wrap;gap:8px;margin:12px 0}.tg{font-size:12px;border:1.5px solid var(--edge);border-radius:999px;padding:3px 10px;color:var(--mid);white-space:nowrap}'
+'.tg.tdd{border-color:#7EB8D4;color:#7EB8D4}.tg.owner,.tg.storyboard,.tg.design-firstrun,.tg.product{border-color:#5FD5A6;color:#5FD5A6}.tg.proposed{border-color:#DABF6A;color:#DABF6A}'
+'.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(640px,1fr));gap:22px;margin-top:18px}'
+'.card{background:var(--panel);border:1px solid var(--edge);border-radius:18px;padding:16px 16px 14px;display:flex;flex-direction:column;gap:12px}'
+'.card header{display:flex;align-items:baseline;gap:10px}.card header a{margin-left:auto;font-size:14px}.no{font-size:13px;font-weight:600;color:var(--acc);border:1.5px solid var(--acc);border-radius:999px;padding:1px 9px}'
+'.shots{display:flex;gap:12px;align-items:flex-start}.shots a:first-child{flex:1 1 auto;min-width:0}.shots a:last-child{flex:0 0 22%}'
+'dl{margin:0;display:grid;grid-template-columns:130px 1fr;gap:6px 14px;font-size:14.5px}dt{color:var(--dim);font-weight:600}dd{margin:0;color:var(--ink)}'
+'.tgs{display:flex;flex-wrap:wrap;gap:6px}'
+'.dir{margin-top:26px;background:var(--panel);border:1px solid var(--edge);border-radius:18px;padding:18px}.dir h3{font-size:24px}.dir dl{margin-top:10px}'
+'.srow{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:16px}.srow figure{margin:0;position:relative}.srow figcaption{margin-top:6px;font-size:13px;color:var(--mid)}.srow figcaption b{display:block;color:var(--ink);font-size:14px}'
+'.srow .ph{position:absolute;right:8px;top:8px;width:20%}.srow .ph img{box-shadow:0 4px 14px rgba(0,0,0,.6)}'
+'.strip a{display:block}.strip{margin-top:14px}.strip img{width:100%}.strip .m{margin-top:12px}'
+'table{border-collapse:collapse;font-size:14.5px;width:100%;max-width:1100px;margin-top:10px}td,th{border-bottom:1px solid var(--edge);padding:8px 10px;text-align:left;vertical-align:top}th{color:var(--dim);font-weight:600}'
+'.base{display:grid;grid-template-columns:repeat(auto-fill,minmax(420px,1fr));gap:18px;margin-top:14px}.base figure{margin:0}.base figcaption{font-size:14px;color:var(--mid);margin-top:6px}.base .p2{display:flex;gap:10px}.base .p2 a:last-child{flex:0 0 22%}'
+'ul{max-width:92ch;padding-left:20px}li{margin:4px 0}code{background:var(--panel);padding:1px 6px;border-radius:6px;font-size:.92em}'
+'@media (max-width:700px){.grid{grid-template-columns:1fr}.srow{grid-template-columns:1fr}dl{grid-template-columns:1fr}.shots a:last-child{flex-basis:28%}.base{grid-template-columns:1fr}h1{font-size:30px}}'
+'</style></head><body><div class="wrap">'
+'<h1>Onboarding and tutorial mockups</h1><p class="lead">Login, onboarding, tutorial. Round OT. Mockups only: nothing in <code>atuned_src/</code> changed, nothing was built into <code>source.html</code>, nothing was pushed. Every page runs from a file with no network. The font is the product’s own Inter, carried in the file.</p>'
+'<nav><a href="#baseline">Baseline</a><a href="#login">Login, three directions</a><a href="#onboarding">Onboarding</a><a href="#strips">Frame strips</a><a href="#tutorial">Tutorial and questions</a><a href="#ten">The first ten laws</a><a href="#checks">Checks</a><a href="#open">Open questions</a></nav>'
+'<div class="key"><span class="tg tdd">TDD</span><span class="tg owner">owner, storyboard, DESIGN-firstrun, product</span><span class="tg proposed">PROPOSED</span></div>'
+'<p class="small">Every frame is drawn at 1600 by 1000 (large image) and 390 by 844 (narrow image). Click an image for the full file. Times are Judgement unless the line says measured. All frames are the Dark lighting. Snow, Punch and Glass are not drawn: the drawing uses the product’s tokens and a lighting swap is a build step, not a redraw, but that was not proved here.</p>'
+'<h2 id="firstpaint">First paint, in one line</h2><p>Ship the login as static markup inside the first byte of the document with a one line script in the head that adds <code>html.door</code>, and have the CSS keep the app root at <code>visibility:hidden</code> under that class until <code>loginClose()</code> or a held session removes it, so the app is never painted behind the door.</p>'
+'<p class="small">Today the first paint is the boot overture and then the login card over a dimmed live app, which is the flash. See baseline below.</p>'
+'<h2 id="baseline">Baseline: what a stranger sees today</h2><p class="small">Taken from <code>source.html</code> in Chromium at both widths, and the funnel page from <code>funnel/index.html</code>. All in <code>baseline/</code>.</p><div class="base">'
+base.map(function(b){return '<figure><div class="p2"><a href="'+b[0]+'"><img loading="lazy" src="'+b[0]+'" alt="'+b[2]+'"></a><a href="'+b[1]+'"><img loading="lazy" src="'+b[1]+'" alt="'+b[2]+' narrow"></a></div><figcaption><b>'+b[2]+'.</b> '+b[3]+'</figcaption></figure>';}).join('')+'</div>'
+'<h2 id="login">Login: three directions</h2><p class="lead">All three: username and passphrase, no email field on the sign in, sign up lets the person choose the username, the button reads Guest, Developer options is small in the lower right, and the ground is the Field’s own grammar in 2D. Every motion is a state, and every motion stops under reduced motion with the final state drawn. My pick is A, because the owner already ruled the login belongs on the boot screen and A is that screen. That is a recommendation, not a decision.</p>'
+login.map(function(L){return '<section class="dir" id="login-'+L.d+'"><h3>'+L.name+' <a href="'+L.live+'" style="font-size:15px;font-weight:400">Open live and type into it</a></h3><p>'+L.line+'</p>'+states(L.d,L.st)
 +'<dl><dt>At a glance</dt><dd>'+L.glance+'</dd><dt>Costs the person</dt><dd>'+L.person+'</dd><dt>Costs to build</dt><dd>'+L.build+'</dd><dt>What each motion means</dt><dd>'+L.grammar+'</dd></dl></section>';}).join('')
+'<h2 id="onboarding">Onboarding frames</h2><p class="lead">The five nodes at the top right fill in as the person goes: said, noticed, tested, worked with it, observed. They are the Field remembering, they carry no count, and they are the same five the handoff names. Live: <a href="onboarding.html">onboarding.html</a>, which clicks through.</p><div class="grid">'+onb.map(card).join('')+'</div>'
+'<h2 id="strips">Frame strips, the two animated scenes</h2><p class="lead">Same drawing code as the live animation. Each frame is one grammar word.</p>'
+'<div class="strip"><h3>Mirror forming</h3><a href="png/strip-mirror-1600.png"><img loading="lazy" src="png/strip-mirror-1600.png" alt="Mirror forming, six frames"></a><p class="small">Signal, Notice, Connect, Pattern, Body, Mirror. Stack at 390: <a href="png/strip-mirror-390.png">png/strip-mirror-390.png</a>. Live: <a href="strips.html#mirror">strips.html#mirror</a>.</p></div>'
+'<div class="strip"><h3>Release states</h3><a href="png/strip-release-1600.png"><img loading="lazy" src="png/strip-release-1600.png" alt="Release states, six frames"></a><p class="small">Held tight and fixed. Contracted smaller, heavier, ticks pressing in. Releasing: ring breaks, lines bend. Opening: ring wide, ticks out. Settling: ring dotted. Observing: before drawn dotted beside after. Stack at 390: <a href="png/strip-release-390.png">png/strip-release-390.png</a>. Live: <a href="strips.html#release">strips.html#release</a>.</p></div>'
+'<h2 id="tutorial">Tutorial and the skippable questions</h2><p class="lead">The loop is a ring and is the only progress object. Each station is shown being done, then named. Live: <a href="tutorial.html">tutorial.html</a>. The questions sit after the handoff and are skippable at every step, which is the review’s option B. Putting them before the handoff, as the TDD does, is a re-order and nothing else.</p><div class="grid">'+tut.map(card).join('')+'</div>'
+'<h2 id="ten">The first ten laws, round PB</h2><p class="lead">His ten, and the order they are asked in: the body from the bottom to the top. Three of them are written out in both formats, so the owner can see the same law as a real moment and as a dilemma. The other seven are not written. Live: <a href="tutorial.html#laws">tutorial.html#laws</a>.</p>'
+'<table><tr><th>Question</th><th>Law</th><th>Seat</th></tr>'+[['1','Patience','Root'],['2','Temperance','Sacral'],['3','Duty','Solar plexus'],['4','Accountability','Solar plexus'],['5','Compassion','Heart'],['6','Forgiveness','Heart'],['7','Truth','Throat'],['8','Transparency','Throat'],['9','Humility','Third eye'],['10','Unity','Crown']].map(function(r){return '<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+r[2]+'</td></tr>';}).join('')+'</table><div class="grid">'+ten.map(card).join('')+'</div>'
+'<h2 id="checks">Checks, and what they found</h2><ul>'
+'<li><b>Voice gate</b> (<code>check.py --line</code>) on every sentence of rendered text across all 43 pages, 103 lines of three words or more: 101 clean on the first run. The two flagged were mine and are rewritten: “How do you actually operate?” failed the plain words list on “operate”. The same gate fails two of the TDD’s own lines: “Welcome to a somatic experience.” fails as a preamble, and “Most people operate somewhere in the middle.” fails on “operate”. Run on the source files, <code>check.py</code> reports two figure label failures in <code>flow.js</code>; both are the signal chips (a phrase and a colour in one array) and are false positives of the gate’s row shape, not copy.</li>'
+'<li><b>Contrast</b>, against each element’s own ground, Dark. Text: ink 16.6, mid 9.0, dim 6.1 (5.8 on the Login B plate), accent 9.0, button label on accent 8.6, alarm text 6.9. Seat rings against the ground 4.8 (Root) to 6.6 (Third eye). Two defects found and fixed: control borders were white at 16 percent, 1.56 to 1, and are now 38 percent, 3.54 to 1; the quiet starting points were at half opacity and their labels measured 3.0, and they are now at 75 percent, 5.4. The unlit field ticks are decoration and are left below 3 on purpose. Today’s login input border is about 1.5 to 1.</li>'
+'<li><b>Tap targets</b>, 403 controls across all 43 pages at both widths, measured from the rendered boxes: 0 under 44 by 44 after fixing the sign in switch (40) and the Type and Speak switch (43).</li>'
+'<li><b>No em dashes</b> in any source file, and sentence case throughout.</li>'
+'<li><b>Round PB frames</b> (the laws list, the six worked questions and the starting points note) went through the voice gate line by line, all clean. They were not put through the contrast and tap target sweeps above, which were run on the 43 pages of round OT. Run those before relying on them.</li>'
+'<li><b>Not done:</b> Snow, Punch and Glass lightings; a keyboard walk; a screen reader pass; the real engine behind any frame. These are drawings.</li></ul>'
+'<h2 id="open">Open, and whose call</h2><ul>'
+'<li><b>Account order.</b> These mockups put the account door first, as the owner asked for the login, and keep Guest as a first class entry. The TDD puts the account before the first release and the earlier storyboards put it after. The review recommends after (question 1). Frame O14 shows the after version for a Guest.</li>'
+'<li><b>Username needs a server change.</b> The server keys an account on the email today (<code>ui/login.js</code> notes it). Username sign in with no email needs a username field there, and a way back in when a passphrase is lost, which an email would have done. Nothing here draws recovery.</li>'
+'<li><b>The mapping from a starting point to a seat</b> is PROPOSED. There is no such table. Pain lights Root here, on the same footing as the others.</li>'
+'<li><b>Twelve starting points.</b> The main version is twelve. Whether it is too many is read off three measures, and none of them can be counted inside the product while the privacy policy says nothing about use is reported.</li>'
+'<li><b>Eleven laws wait.</b> Non-harm, Courage, Responsibility, Detachment, Generosity, Aesthetic beauty, Justice, Presence, Equanimity, Awareness and Nature are not in his ten. When they are asked, and whether they ever are, is not ruled.</li>'
+'<li><b>Release sentence.</b> The TDD sentence is on the screen as a placeholder; the ruled one is “letting go” with six verbs.</li></ul>'
+'<p class="small">Rebuild: <code>node mockups/onboarding/build.js</code> then <code>node mockups/onboarding/make-index.js</code>. Sources in <code>mockups/onboarding/src/</code>.</p>'
+'</div></body></html>';
fs.writeFileSync(path.join(root,'index.html'),html);
console.log('index.html',Math.round(html.length/1024)+' KB');
